### PR TITLE
rotate and STAY

### PR DESCRIPTION
**Pull request by quitequinn**
Where are you going rotate, always in a rush, stay a while.

### CODE REVIEW

**Comment by darielnoel** [comment]
Great :). Could you please update the metada? 

For example...

```
/*
 *@name rotate
 *@className rotate animated
 *@cssCode
 *@editionLink codepen.io
 *@author Quinn Keaveney
 *@source AniCollection
 *@sourceUrl https://github.com/anicollection/anicollection
 *@issues https://github.com/anicollection/anicollection/issues
 *@license Your License
*/
```

**Comment by quitequinn** [comment]
you don't want you name? haha
- ℚ

twitter. @QuiteQuinn https://twitter.com/QuiteQuinn
web. quitetype.com
b[log]. iknowthatsign.com

**Comment by darielnoel** [comment]
No thanks :). Those are your animations.

**Comment by darielnoel** [comment]
+1

**Pull request merged**
